development:
  clients:
    default:
      database: dataops_challenge_development
      hosts:
        - localhost:27017
      options:
        user: root
        password: example
        auth_source: admin
        retry_writes: false
